### ISSUE TITLE
How do I use an instance of discovery I already have? 

### ISSUE THREAD

**Issue by fatemaRam** [IBM/watson-discovery-ui#151]
I've added the .env file with my own environment id, api and collection id, but deployment still fails every time. What else do I need to change? Thank you for any help 

FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: You can only have one instance of a Lite plan per service. To create a new instance, either delete your existing Lite plan instance or select a paid plan.

Finished: FAILED

**Comment by rhagarty** [comment]
Hi @fatemaRam - I'm not quite sure what path you are attempting. Are you running in the cloud by using the "Deploy to IBM Cloud" button, or are you trying to install and run locally?

Since you created a discovery service and created an `.env` file, it would seem like you are trying to run locally. But when you mention `deployment`, it would indicate running on the IBM Cloud.

Please provide more detail so I can better diagnose your issue.

FYI - if you press the "Deploy" button, your local `.env` file is ignored. BUT, if you have an existing Watson Discovery service named `wdui-discovery-service`, the deploy process should find it and deploy correctly. If your service has a different name, it will try to use it, but may run into service limitations due to number of private collections you can have. If this is what you are running into, I would suggest renaming your service and trying again.

**Comment by SBSsbs** [comment]
Good morning [fatemaRam](/fatemaRam)

In the Message it is indicated:
***************************************************************************
Service broker error: You can only have one instance of a Lite plan per service.
****************************************************************************
I guess you are using a lite plan which does not allow you to create more than two instances with watson discovery so you need to delete all the other instances and keep only two

**Comment by rhagarty** [comment]
@fatemaRam - haven't heard back from you so I am assuming you got past this issue.
