### ISSUE TITLE
Again I tried the uRL in different formats and I always find error 

### ISSUE THREAD

**Issue by samaa** [IBM/watson-discovery-ui#154]
I get this error when trying to rum npm start
Invalid URI "%3Chttps://discovery-us-south.watsonplatform.net/regions/us-south/services/436a1ef6158b405fb8fb64b28278eec1%3E/v1/environments". Also I cannot find log files at the path provided 

/Users/elnagarsa/.npm/_logs/2019-02-14T22_43_21_312Z-debug.log
SOB-elnagarsa:watson-discovery-ui elnagarsa$

**Comment by rhagarty** [comment]
@samaa - sorry your running into issues, but I really need more information to help diagnose the problem. There are a number of ways to install and run this application, so you need to detail the steps you took to get to this point.

Since you are using `npm start`, I assume you have created your Discovery service and placed the credentials in your `.env` file. The URL for this service is shown in the service credentials panel for the service. Your discovery URL should look something like this:

DISCOVERY_URL=https://gateway.watsonplatform.net/discovery/api

**Comment by samaa** [comment]
I tried to put the url on the form u gave me and here screen shot of env.sample and screen shot of bash

**Comment by samaa** [comment]
https://ibb.co/hc7KH33
https://ibb.co/Rp8C4qq

**Comment by rhagarty** [comment]
@samaa - couple of issues.
1) you need to remove the brackets `<` from the .env file. They are meant to indicate that you need to substitute the values. Your values should be similar to:
```
DISCOVERY_URL=https://gateway.watsonplatform.net/discovery/api
DISCOVERY_USERNAME=elnagarsa@vcu.edu
DISCOVERY_PASSWORD=*******
```
2) Please check the credentials created for your Watson Discovery service. Make sure it is using uname/password. In most regions, the service is now using `apikey`. This is explained in the comments of the .env file.

**Comment by stevemart** [comment]
@samaa one other thing to note is that `DISCOVERY_USERNAME` is **not** your IBM Cloud username. It's based on the credentials of the Discovery service (and typically a random string, not an email). You can see this after you create the service in the "service credentials" tab it'll look like this below.

![](https://www.ibm.com/cloud/garage/images/tutorials/cognitive_discovery/bmx-service-credentials1.png)

**Comment by samaa** [comment]
It worked Thanks alot :)))))
